CFLAGS = -Wall -g -pthread
LIBS = -L./ -lksocket

all: initksocket

initksocket: initksocket.o
	gcc $(CFLAGS) -o initksocket initksocket.o $(LIBS)

initksocket.o: initksocket.c ksocket.h
	gcc $(CFLAGS) -c initksocket.c

clean:
	rm -f initksocket *.o
